# Generated by Django 4.0.3 on 2022-03-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todoitem',
            managers=[
            ],
        ),
    ]
